services:
  - type: web
    name: homeservicesetc-dynamic
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ORIGIN
        value: "*"
